version: "3"
services:
  server:
    image: elyspio/haproxy-virtualizer:arm64
    ports:
      - "4001:4000"
    environment:
      LOG_FOLDER: /var/logs
    volumes:
      - /etc/haproxy/haproxy.cfg/:/etc/haproxy/haproxy.cfg
      - /apps/haproxy-virtualizer/logs:/var/logs
      - /apps/haproxy-virtualizer/accounts.json:/app/accounts.json
    restart: always
    container_name: haproxy-visualizer
